### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by tldyl**

### CODE REVIEW

**Comment by hsluoyz** [comment]
Please do not generate "Merge branch" commit like:

image

Do git rebase or reset to remove it.

**Comment by hsluoyz** [comment]
Why is it named `shiro-jcasbin-spring-boot-starter`? Why is there Springboot?

**Comment by tldyl** [comment]
It uses some annotations in Spring Boot to implement automatic configuration.
Of course, if you want to use a plugin for Spring, I can make another one.

**Comment by hsluoyz** [comment]
Better do not depend on Spring. I want this to replace Shiro in all cases.

**Pull request closed without merging**
